language: julia

julia:
  - 1.5.1

os:
  - osx

notifications:
  email:
    - vallsdev@tcd.ie

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
